---
- name: Make sure we have a sudo group
  group:
    name: sudo
    state: present
- name: Allow sudo group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
  # TODO: Could use community.general.sudoers here
- name: Add sudoers users to sudo group
  user:
    name: "{{ add_ansible_user }}"
    groups: sudo
    append: yes
    state: present
    createhome: yes
- name: Set up authorized keys for the deployer user
  authorized_key: 
    user: "{{ add_ansible_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ add_ansible_pubkey }}"
