---
- name: roms
  copy:
    src: "/data/roms/{{ inventory_hostname }}/"
    dest: "/home/{{ pi_user }}/RetroPie/roms"
- copy:
    src: /data/roms/bios
    dest: /home/pi/RetroPie/BIOS
- name: Disable runcommand
  lineinfile:
    path: /opt/retropie/configs/all/runcommand.cfg
    state: present 
    line: disable_menu = "1"
    regexp: ^disable*