---
- name: roms
  copy:
    src: "/data/roms/{{ inventory_hostname }}/"
    dest: "/home/{{ pi_user }}/RetroPie/roms"
- copy:
    src: /data/roms/bios
    dest: /home/pi/RetroPie/BIOS
- name: Disable runcommand
  lineinfile:
    path: /opt/retropie/configs/all/runcommand.cfg
    state: present 
    line: disable_menu = "1"
    regexp: ^disable*
# Hint: Use RetroArch (launched from EmulationStation, not mid-game) to rotate in-game.
# enable 'advanced options' and 'save current configuration' and restart RetroArch to get the video rotate option.
# Settings - Video - Output - Video Rotation - 90 deg
# Conffiguration File - Save Current Configuration
- name: Rotate for vertical monitor
  lineinfile:
    path: "{{ item }}"
    state: present 
    line: emulationstation --screenrotate 3 --resolution 960 1280
    regexp: ^emulationstation*
  with_items:
    - /opt/retropie/configs/all/autostart.sh
    #    - /home/pi/.profile
# Tip: Solved missing audio on Pi2/Pi3 by adding 
#  snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1 snd_bcm2835.enable_compat_alsa=1
#  to the one line in
#  /boot/cmdline.txt
#  This won't work on Armbian based build, since that file is not present.
