---
 - name: install learning software
   apt:
     name:
      - atomix
      - dosbox
      - education-menus
      - einstein
      - glpeces
      - gnuchess
      - lmemory
      - ri-li
      - tuxmath
      - tuxpaint
      - tuxtype
# - name: get ye some Python
#   apt:
#     name: 
#      - python3-pip
# - pip:
#     name: PythonTurtle
 - name: Copy dosbox files
   unarchive:
     src: "{{ item }}"
     dest: "{{ dosbox_files }}"
   with_fileglob:
     - "{{ dosbox_files }}/*"
 - name: tic80
   apt: tic80
