---
# tasks file for lab-desktop
- name: Add remote desktop
  apt:
    update_cache: true
    name:
      - xrdp
      - xorgxrdp
- name: Enable remote desktop
  systemd:
    name: xrdp
    enabled: yes
    state: started
- name: Remove first login script
  file: 
    path: /etc/profile.d/armbian-check-first-login.sh
    state: absent

