---
- name: Setup a new arcade machine
  gather_facts: no
  hosts: arcades
  become: yes
  vars:
    - pi_user: pi

  tasks:
    - name: Add retropie
      import_role:
        name: retropie
    - name: Add roms
      import_role:
        name: arcade


