---
- name: Setup a new arcade machine
  gather_facts: no
  hosts: new_arcades
  vars:
    - new_hostname: pacman
  become: yes

  tasks:
    # Run with --ask-become-pass the first time
    # Remember to set vars ansible_admin and ansible_pubkey
    - name: setup admin
      include_role:
        name: school_admin

