---
- name: Add hostname
  gather_facts: no
  hosts: new
  vars_prompt:
    - name: new_hostname
      prompt: New hostname?
      private: false
      #    - name: motd_file
      #prompt: Message file?
      #private: false
  become: yes

  tasks:
    - name: Remove default hostname
      lineinfile:
        state: absent
        path: /etc/hostname
        line: "{{ item }}"
      with_items:
        - lepotato
        - renegade
        - retropie
    - name: Add to /etc/hostname
      lineinfile:
        state: present
        path: /etc/hostname
        line: "{{ new_hostname }}"
    - name: Add to /etc/hosts
      lineinfile:
        state: present
        path: /etc/hosts
        line: "127.0.0.1    {{ new_hostname }}"
    - name: Add message of the day
      copy:
        src: "~/motd/{{ new_hostname }}"
        dest: /etc/motd

