---
- name: Setup a new Armbian host
  gather_facts: yes
  hosts: new
  become: yes
  vars:
    add_ansible_pubkey: ~/.ssh/id_ed25519.pub
    
  tasks:
    # - name: Allow changes on Recallbox
    #  include_role:
    #    name: unlock_recalbox
    # Run with --ask-become-pass the first time
    - name: Add remote login
      include_role:
        name: new

