---
- name: Setup a new Armbian host
  gather_facts: no
  hosts: new
  become: yes
  vars_prompt:
    - name: ansible_user
      prompt: login user?
    - name: ansible_ssh_pass
      prompt: login password?


  tasks:
    # Run with --ask-become-pass the first time
    # Remember to set vars ansible_admin and ansible_pubkey
    - name: Add remote login
      include_role:
        name: lab_new

