---
- name: Setup a new arcade machine
  gather_facts: no
  hosts: armbian
  become: yes
  vars:
    - pi_user: pi

  tasks:
    - name: setup admin
      include_role:
        name: school_admin
    - user:
        name: "{{ pi_user }}"
        comment: Arcade Player
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
        createhome: yes
    - name: Install retropie setup script
      include_role:
        name: retropie
      vars:
        clone_to: "/home/{{ pi_user }}/Retropie-Setup"
    - name: login with no password
      lineinfile:
        path: /lib/systemd/system/getty@.service
        line: "ExecStart=/sbin/agetty --noclear --autologin {{ pi_user }} %I $TERM"
        regexp: "^ExecStart.*"
    - name: reminder
      debug:
        msg: "login and run __platform=genericx11 ~/Retropie-Setup/retropie-setup.sh"
