---
- name: Setup school computers
  gather_facts: no
  hosts: school
  vars:
    - install_root: /usr/tic80
  vars_prompt:
    - name: student_password
      prompt: Student password
      private: true
      encrypt: sha512_crypt
  become: yes

  tasks:
    - name: Add school
      import_role:
        name: schoolbox

