---
- name: Setup school computers
  gather_facts: no
  hosts: school
  vars:
    - install_root: /usr/tic80
  become: yes

  tasks:
    # Run with --ask-become-pass the first time
    # Remember to set vars ansible_admin and ansible_pubkey
    - name: setup admin
      include_role:
        name: school_admin
    - name: Install school software
      include_role:
        name: schoolbox

