name: Peanut Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-the-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install make
      run: sudo apt-get install make python
    - name: run tests
      run: make test