name: Peanut Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-the-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install make python3
    - name: install libs
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run tests
      run: make test