name: Peanut Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-the-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install make python
    - name: install libs
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pygame
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: style check
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: run tests
      run: make test